# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0002_auto_20170321_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionary',
            new_name='Questionnaire',
        ),
    ]
