# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0003_auto_20170321_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='remarks',
            field=models.TextField(verbose_name='You can add any comment or note (e.g. if something important happened, how do you feel etc.)'),
        ),
    ]
