# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychology', '0004_auto_20170521_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-datetime'], 'verbose_name': 'Questionnaires'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='astronaut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
    ]
