# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0005_auto_20170521_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-datetime'], 'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
    ]
