# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_intoxication_pulsoxymetry_qualityoflife_sex_sleep_temperature_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sex',
            new_name='Intercourse',
        ),
    ]
