# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_auto_20170819_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time')),
                ('start', models.TimeField(blank=True, default=True, null=True, verbose_name='Start')),
                ('end', models.TimeField(blank=True, default=True, null=True, verbose_name='End')),
                ('objectives', models.TextField(verbose_name='Contingencies')),
                ('participants', models.TextField(verbose_name='Participants')),
                ('contingencies', models.TextField(verbose_name='Contingencies')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Extra-Vehicular Activity',
                'verbose_name_plural': 'Extra-Vehicular Activities',
            },
        ),
        migrations.CreateModel(
            name='Contingency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time')),
                ('identifier', models.CharField(max_length=10, unique=True, verbose_name='Identifier')),
                ('severity', models.CharField(choices=[('emergency', 'Emergency - ABORT the simulation'), ('critical', 'Critical - ABORT the EVA'), ('warning', 'Warning'), ('info', 'Informative')], default='info', max_length=30, verbose_name='Severity')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('recovery_procedure', models.TextField(verbose_name='Recovery Procedure')),
                ('remarks', models.TextField(verbose_name='Additional Remarks')),
            ],
            options={
                'verbose_name': 'Contingency',
                'verbose_name_plural': 'Contingencies',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time')),
                ('identifier', models.CharField(max_length=10, unique=True, verbose_name='Identifier')),
                ('estimated_duration', models.DurationField(blank=True, default=True, null=True, verbose_name='Estimated Duration')),
                ('objective', models.TextField(verbose_name='Objective')),
                ('remarks', models.TextField(verbose_name='Additional Remarks')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time')),
                ('start', models.TimeField(blank=True, default=True, null=True, verbose_name='Start')),
                ('end', models.TimeField(blank=True, default=True, null=True, verbose_name='End')),
                ('objectives', models.TextField(verbose_name='Contingencies')),
                ('description', models.TextField(verbose_name='Description')),
                ('contingencies', models.TextField(verbose_name='Contingencies')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
