# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='objectives',
        ),
        migrations.AddField(
            model_name='report',
            name='primary_objectives',
            field=models.ManyToManyField(related_name='primary_objectives', to='extravehicular.Objective', verbose_name='Primary Objectives'),
        ),
        migrations.AddField(
            model_name='report',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Contingencies'),
        ),
        migrations.AddField(
            model_name='report',
            name='secondary_objectives',
            field=models.ManyToManyField(blank=True, default=None, related_name='secondary_objectives', to='extravehicular.Objective', verbose_name='Secondary Objectives'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('success-full', 'Full Success'), ('success-primary', 'Primary Objectives Done'), ('success-partial', 'Partial Success'), ('todo', 'To Do'), ('in-progress', 'In Progress'), ('aborted', 'Aborted')], default='todo', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contingencies',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Contingencies'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
    ]
