# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0002_auto_20170821_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('file', models.FileField(upload_to='report/', verbose_name='Attachment')),
            ],
            options={
                'verbose_name': 'Report Attachment',
                'verbose_name_plural': 'Report Attachments',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('exploratory', 'Exploratory'), ('experimental', 'Experimental'), ('operational', 'Operational'), ('emergency', 'Emergency')], default='operational', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('success-full', 'Full Success'), ('success-primary', 'Primary Objectives Done'), ('success-partial', 'Partial Success'), ('todo', 'To Do'), ('in-progress', 'In Progress'), ('aborted', 'Aborted')], default='todo', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spacewalker',
            name='designation',
            field=models.CharField(choices=[('ev-leader', 'Lead Spacewalker'), ('ev-support', 'Supporting Spacewalker'), ('habitat-support', 'Habitat Support'), ('rover-operator', 'Rover Operator')], max_length=30, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extravehicular.Report', verbose_name='Report'),
        ),
    ]
