# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0003_auto_20170821_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
