# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extravehicular', '0003_auto_20170819_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingency',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contingency',
            name='time',
        ),
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='time',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='date',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='time',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='extravehicular.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contingency',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional Remarks'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='extravehicular.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='extravehicular.Location', verbose_name='Location'),
        ),
    ]
