# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import habitat._common.models.date


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0003_auto_20170822_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.CharField(default=habitat.timezone.LunarStandardTime.date, help_text='Lunar Standard Time', max_length=15, verbose_name='Mission Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(default=habitat.timezone.LunarStandardTime.date, help_text='Lunar Standard Time', max_length=15, verbose_name='Mission Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
