# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0004_auto_20170825_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='estimated_duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Estimated Duration'),
        ),
        migrations.AlterField(
            model_name='report',
            name='end',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Start'),
        ),
    ]
