# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0004_auto_20170819_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Mission Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Mission Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
