# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0004_auto_20170821_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
    ]
