# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0005_auto_20170828_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacewalker',
            name='objectives',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Objectives'),
        ),
    ]
