# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('extravehicular', '0006_spacewalker_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tools',
        ),
        migrations.AddField(
            model_name='activity',
            name='tools',
            field=models.ManyToManyField(blank=True, default=None, to='inventory.Item', verbose_name='Tools'),
        ),
    ]
