# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extravehicular', '0008_auto_20170906_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
