# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-value']},
        ),
        migrations.AddField(
            model_name='temperature',
            name='unit',
            field=models.CharField(choices=[('celsius', 'Celsius'), ('kelvin', 'Kelvin'), ('fahrenheit', 'Fahrenheit')], default='celsius', max_length=10, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='Temperature'),
        ),
    ]
