# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_auto_20170520_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Luminosity',
            new_name='Luminance',
        ),
    ]
