# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_auto_20170521_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humidity',
            options={'ordering': ['-value'], 'verbose_name': 'Humitdity Measurement', 'verbose_name_plural': 'Humidity Measurements'},
        ),
        migrations.AlterModelOptions(
            name='luminance',
            options={'ordering': ['-value'], 'verbose_name': 'Luminance Measurement', 'verbose_name_plural': 'Luminance Measurements'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-value'], 'verbose_name': 'Temperature Measurement', 'verbose_name_plural': 'Temperature Measurements'},
        ),
    ]
