# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biolab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='spicies',
            new_name='species',
        ),
    ]
