# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalnote',
            options={'ordering': ['-modified_date']},
        ),
    ]
