# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20170520_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-modified_date'], 'verbose_name': 'Diary Entry', 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AlterModelOptions(
            name='figure',
            options={'ordering': ['-diary_entry'], 'verbose_name': 'Figure', 'verbose_name_plural': 'Figures'},
        ),
        migrations.AlterModelOptions(
            name='personalnote',
            options={'ordering': ['-modified_date'], 'verbose_name': 'Personal Note', 'verbose_name_plural': 'Personal Notes'},
        ),
    ]
