# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkingWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('volume', models.DecimalField(decimal_places=2, default=None, help_text='liters', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9.99)], verbose_name='Volume')),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Drinking Water Measurement',
                'verbose_name_plural': 'Drinking Water Usage',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='GreenWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('volume', models.DecimalField(decimal_places=2, default=None, help_text='liters', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9.99)], verbose_name='Volume')),
                ('usage_description', models.TextField(blank=True, default=None, null=True, verbose_name='Usage Description')),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Green Water Measurement',
                'verbose_name_plural': 'Green Water Usage',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('volume', models.DecimalField(decimal_places=2, default=None, help_text='liters', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9.99)], verbose_name='Volume')),
                ('usage_description', models.TextField(blank=True, default=None, null=True, verbose_name='Usage Description')),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Technical Water Measurement',
                'verbose_name_plural': 'Technical Water Usage',
                'ordering': ['-datetime'],
            },
        ),
    ]
