# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20170818_0635'),
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenwater',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Usage Location'),
        ),
        migrations.AddField(
            model_name='technicalwater',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Usage Location'),
        ),
    ]
