# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkingwater',
            options={'verbose_name': 'Drinking Water Usage', 'verbose_name_plural': 'Drinking Water'},
        ),
        migrations.AlterModelOptions(
            name='greenwater',
            options={'verbose_name': 'Green Water Usage', 'verbose_name_plural': 'Green Water'},
        ),
        migrations.AlterModelOptions(
            name='technicalwater',
            options={'verbose_name': 'Technical Water Usage', 'verbose_name_plural': 'Technical Water'},
        ),
        migrations.RenameField(
            model_name='drinkingwater',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='greenwater',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='technicalwater',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RemoveField(
            model_name='drinkingwater',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='greenwater',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='technicalwater',
            name='datetime',
        ),
        migrations.AddField(
            model_name='drinkingwater',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkingwater',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='greenwater',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenwater',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='technicalwater',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalwater',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
    ]
