# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20170819_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwater',
            name='date',
            field=models.CharField(default=' ', help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='drinkingwater',
            name='time',
            field=models.TimeField(default='12:33', help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='greenwater',
            name='date',
            field=models.CharField(default=' ', help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='greenwater',
            name='time',
            field=models.TimeField(default='12:13', help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='technicalwater',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='technicalwater',
            name='time',
            field=models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
    ]
