# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_auto_20170825_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingwater',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='greenwater',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='technicalwater',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
