# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Max crew members working inside.', null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='module',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='m', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='module',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='m', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='module',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='m', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Width'),
        ),
    ]
