# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20170717_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='blueprint',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='modules/', verbose_name='Blueprint'),
        ),
        migrations.AlterField(
            model_name='module',
            name='hazzard',
            field=models.CharField(choices=[('none', 'Working Nominal'), ('warning', 'Warning'), ('hazardous', 'Hazardous'), ('toxic', 'Toxic'), ('depress', 'Hazardous'), ('fire', 'Fire'), ('disabled', 'Disabled')], db_index=True, default=None, max_length=30, verbose_name='Hazzard'),
        ),
    ]
