# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20170717_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='blueprint',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='modules/', verbose_name='Blueprint'),
        ),
    ]
