# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20170719_2220'),
    ]

    operations = [
	migrations.RenameField(
            model_name='module',
            old_name='hazzard',
            new_name='hazard',
        ),
    ]
