# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20170719_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='hazzard',
        ),
        migrations.AddField(
            model_name='module',
            name='hazard',
            field=models.CharField(choices=[('none', 'None'), ('warning', 'Warning'), ('hazardous', 'Hazardous'), ('toxic', 'Toxic'), ('depress', 'Hazardous'), ('fire', 'Fire'), ('disabled', 'Disabled')], db_index=True, default=None, max_length=30, verbose_name='Hazard'),
        ),
    ]
