# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0004_auto_20170325_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressure',
            name='astronaut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
