# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 19:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0005_bloodpressure_astronaut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['-datetime_start']},
        ),
        migrations.AlterModelOptions(
            name='pulsoxymetry',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='sleep',
            options={'ordering': ['-datetime_start']},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='disease',
            name='astronaut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='datetime_end',
            field=models.DateTimeField(default=None, verbose_name='End Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='datetime_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Datetime'),
        ),
        migrations.AddField(
            model_name='disease',
            name='icd10',
            field=models.CharField(default=None, max_length=50, verbose_name='ICD-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='sympthoms',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulsoxymetry',
            name='astronaut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulsoxymetry',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='astronaut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleep',
            name='datetime_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='datetime_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='quality',
            field=models.CharField(choices=[('very bad', 'Very Bad'), ('bad', 'Bad'), ('average', 'Average'), ('good', 'Good'), ('very good', 'Very Good')], max_length=30, default='average', verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='astronaut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=36.6, max_digits=3, validators=[django.core.validators.MaxValueValidator(42), django.core.validators.MinValueValidator(30)], verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='weight',
            name='BMI',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(10)], verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='weight',
            name='astronaut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=70.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(130), django.core.validators.MinValueValidator(30)], verbose_name='Weight'),
        ),
    ]
