# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 19:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20170520_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='Celsius', max_digits=3, validators=[django.core.validators.MaxValueValidator(42), django.core.validators.MinValueValidator(30)], verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BMI',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(10)], verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(130), django.core.validators.MinValueValidator(30)], verbose_name='Weight'),
        ),
    ]
