# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20170520_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='datetime_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='quality',
            field=models.CharField(blank=True, choices=[('very bad', 'Very Bad'), ('bad', 'Bad'), ('average', 'Average'), ('good', 'Good'), ('very good', 'Very Good')], default=None, max_length=30, null=True, verbose_name='Quality'),
        ),
    ]
