# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_auto_20170520_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='body_fat',
            field=models.DecimalField(decimal_places=1, default=None, help_text='%', max_digits=3, blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Body Fat'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='body_water',
            field=models.DecimalField(decimal_places=1, default=None, help_text='kg', max_digits=4, blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Body Water'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='bone_mass',
            field=models.DecimalField(decimal_places=1, default=None, help_text='kg', max_digits=4, blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Bone Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='daily_caloric_intake',
            field=models.PositiveIntegerField(default=None, help_text='kcal', blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4000), django.core.validators.MinValueValidator(0)], verbose_name='Daily Caloric Intake'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='lean_body_mass',
            field=models.DecimalField(decimal_places=1, default=None, help_text='%', blank=True, null=True, max_digits=4, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Lean Body Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='muscle_mass',
            field=models.DecimalField(decimal_places=1, default=None, help_text='kg', blank=True, null=True, max_digits=4, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Muscle Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='visceral_fat',
            field=models.PositiveSmallIntegerField(default=None, blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Visceral Fat'),
        ),
    ]
