# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_auto_20170521_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='BMI',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(10)], verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='body_fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='%', max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Body Fat'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='body_water',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='kg', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Body Water'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='bone_mass',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='kg', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Bone Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='daily_caloric_intake',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='kcal', null=True, validators=[django.core.validators.MaxValueValidator(4000), django.core.validators.MinValueValidator(0)], verbose_name='Daily Caloric Intake'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='lean_body_mass',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='%', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Lean Body Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='kg', max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Muscle Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='visceral_fat',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Visceral Fat'),
        ),
    ]
