# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 08:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_bloodpressure_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.PositiveSmallIntegerField(default=None, help_text='mmHg', validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)], verbose_name='Blood Pressure Diastolic'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(default=None, help_text='bpm', validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)], verbose_name='Heart Rate'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.PositiveSmallIntegerField(default=None, help_text='mmHg', validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)], verbose_name='Blood Pressure Systolic'),
        ),
    ]
