# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0016_auto_20170713_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityoflife',
            name='astronaut',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='astronaut',
        ),
        migrations.DeleteModel(
            name='QualityOfLife',
        ),
        migrations.DeleteModel(
            name='Sleep',
        ),
    ]
