# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbondioxide',
            options={'verbose_name': 'Carbon Dioxide Concentration Measurement', 'verbose_name_plural': 'Carbon Dioxide'},
        ),
        migrations.AlterModelOptions(
            name='carbonmonoxide',
            options={'verbose_name': 'Carbon Monoxide Concentration Measurement', 'verbose_name_plural': 'Carbon Monoxide'},
        ),
        migrations.AlterModelOptions(
            name='humidity',
            options={'verbose_name': 'Humidity Measurement', 'verbose_name_plural': 'Humidity'},
        ),
        migrations.AlterModelOptions(
            name='luminance',
            options={'verbose_name': 'Luminance Measurement', 'verbose_name_plural': 'Luminance'},
        ),
        migrations.AlterModelOptions(
            name='meteo',
            options={'verbose_name': 'Meteo', 'verbose_name_plural': 'Meteo Measurements'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Network Performance Measurement', 'verbose_name_plural': 'Network Performance'},
        ),
        migrations.AlterModelOptions(
            name='oxygen',
            options={'verbose_name': 'Oxygen Concentration Measurement', 'verbose_name_plural': 'Oxygen'},
        ),
        migrations.AlterModelOptions(
            name='pressure',
            options={'verbose_name': 'Pressure Measurement', 'verbose_name_plural': 'Pressure'},
        ),
        migrations.AlterModelOptions(
            name='radiation',
            options={'verbose_name': 'Radiation Measurement', 'verbose_name_plural': 'Radiation'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': 'Temperature Measurement', 'verbose_name_plural': 'Temperature'},
        ),
        migrations.AlterModelOptions(
            name='voltage',
            options={'verbose_name': 'Voltage Measurement', 'verbose_name_plural': 'Voltage'},
        ),
        migrations.RemoveField(
            model_name='carbondioxide',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='carbonmonoxide',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='humidity',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='luminance',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='meteo',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='network',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='oxygen',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='radiation',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='voltage',
            name='datetime',
        ),
        migrations.AddField(
            model_name='carbondioxide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbondioxide',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='carbondioxide',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='carbondioxide',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='carbonmonoxide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbonmonoxide',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='carbonmonoxide',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='carbonmonoxide',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='humidity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humidity',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='humidity',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='humidity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='luminance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luminance',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='luminance',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='luminance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='meteo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meteo',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='meteo',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='meteo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='network',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='network',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='network',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxygen',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='radiation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiation',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='radiation',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='radiation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='voltage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voltage',
            name='date',
            field=models.CharField(default=' ', help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='voltage',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='voltage',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
    ]
