# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170819_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voltage',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
    ]
