# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_meteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voltage',
            name='value',
            field=models.DecimalField(decimal_places=3, default=None, help_text='Volts', max_digits=6, verbose_name='Value'),
        ),
    ]
