# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20170818_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbondioxide',
            name='value',
            field=models.DecimalField(decimal_places=3, help_text='%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='carbonmonoxide',
            name='value',
            field=models.DecimalField(decimal_places=3, help_text='%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='value',
            field=models.DecimalField(decimal_places=1, help_text='%', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='network',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Mbps', max_digits=5, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='%', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, help_text='mmHg', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)], verbose_name='Pressure'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='value',
            field=models.DecimalField(decimal_places=5, default=None, help_text='Sievert', max_digits=6, verbose_name='Radiation'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Temperature'),
        ),
    ]
