# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20170825_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbondioxide',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='carbonmonoxide',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='illuminance',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='network',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, help_text='hPa', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)], verbose_name='Pressure'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Location'),
        ),
    ]
