# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('decibel', 'dB'), ('celsius', 'Celsius'), ('kelvin', 'Kelvin'), ('fahrenheit', 'Fahrenheit')], default='celsius', max_length=10, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Value'),
        ),
    ]
