# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import habitat._common.models.date


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_auto_20170925_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZWaveSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=habitat.timezone.LunarStandardTime.date, help_text='Lunar Standard Time', max_length=15, verbose_name='Mission Date')),
                ('time', models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Mission Time')),
                ('datetime', models.DateTimeField(db_index=True, editable=False, verbose_name='Datetime')),
                ('device', models.CharField(db_index=True, max_length=30, verbose_name='Device')),
                ('type', models.CharField(choices=[('battery-level', 'Battery Level'), ('powerlevel', 'Power Level'), ('temperature', 'Temperature'), ('luminance', 'Luminance'), ('relative-humidity', 'Relative Humidity'), ('ultraviolet', 'Ultraviolet')], max_length=30, verbose_name='Type')),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Value')),
                ('unit', models.CharField(choices=[('decibel', 'dB'), ('celsius', 'Celsius'), ('kelvin', 'Kelvin'), ('fahrenheit', 'Fahrenheit')], default='celsius', max_length=10, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'ZWave Sensor Measurement',
                'verbose_name_plural': 'Zwave Sensors',
            },
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
