# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_auto_20170925_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbondioxide',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='carbonmonoxide',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='illuminance',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='network',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='zwavesensor',
            name='time',
            field=models.TimeField(default=habitat.timezone.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
