# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_auto_20170926_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwavesensor',
            name='unit',
            field=models.CharField(blank=True, choices=[(None, 'n/a'), ('percent', '%'), ('lux', 'Lux'), ('decibel', 'dB'), ('celsius', 'Celsius'), ('kelvin', 'Kelvin'), ('fahrenheit', 'Fahrenheit')], default=None, max_length=15, null=True, verbose_name='Unit'),
        ),
    ]
