# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_auto_20170926_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwavesensor',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, verbose_name='Value'),
        ),
    ]
