# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.timezone.models.martian_standard_time


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_auto_20170927_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zwavesensor',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Zwave Sensors'},
        ),
        migrations.AlterField(
            model_name='carbondioxide',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='carbondioxide',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='carbonmonoxide',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='carbonmonoxide',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='illuminance',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='illuminance',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='network',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='network',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='zwavesensor',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='zwavesensor',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
    ]
