# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intercourse',
        ),
        migrations.DeleteModel(
            name='Intoxication',
        ),
        migrations.AlterModelOptions(
            name='bloodpressure',
            options={'verbose_name': 'Blood Pressure', 'verbose_name_plural': 'Blood Pressure'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Disease', 'verbose_name_plural': 'Disease'},
        ),
        migrations.AlterModelOptions(
            name='pulseoxymetry',
            options={'verbose_name': 'Pulse Oxymetry', 'verbose_name_plural': 'Pulse Oxymetry'},
        ),
        migrations.AlterModelOptions(
            name='stool',
            options={'verbose_name': 'Stool', 'verbose_name_plural': 'Stool'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': 'Temperature', 'verbose_name_plural': 'Temperature'},
        ),
        migrations.AlterModelOptions(
            name='urine',
            options={'verbose_name': 'Urine', 'verbose_name_plural': 'Urine'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'verbose_name': 'Weight', 'verbose_name_plural': 'Weight'},
        ),
        migrations.RenameField(
            model_name='bloodpressure',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='pulseoxymetry',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='stool',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='urine',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RemoveField(
            model_name='bloodpressure',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='pulseoxymetry',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='stool',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='urine',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='datetime',
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='disease',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='disease',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='disease',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='pulseoxymetry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulseoxymetry',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='pulseoxymetry',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='pulseoxymetry',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='stool',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stool',
            name='date',
            field=models.CharField(default=' ', help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='stool',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='stool',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='urine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urine',
            name='date',
            field=models.CharField(default=' ', help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='urine',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='urine',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='weight',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='weight',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.PositiveSmallIntegerField(default=None, help_text='mmHg', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Blood Pressure Diastolic'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(default=None, help_text='bpm', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Heart Rate'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.PositiveSmallIntegerField(default=None, help_text='mmHg', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Blood Pressure Systolic'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BMI',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)], verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='body_fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='%', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Body Fat'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='bone_mass',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='kg', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Bone Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='daily_caloric_intake',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='kcal', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)], verbose_name='Daily Caloric Intake'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='lean_body_mass',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='%', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Lean Body Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='kg', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Muscle Mass'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='visceral_fat',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Visceral Fat'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=None, help_text='kg', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Weight'),
        ),
    ]
