# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('volume', models.PositiveIntegerField(blank=True, default=None, help_text='ml', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1700)], verbose_name='Volume')),
                ('color', models.CharField(blank=True, choices=[('brown', 'Brown'), ('yellow', 'Yellow'), ('gray', 'Gray'), ('pale', 'Pale'), ('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('silver', 'Silver'), ('green', 'Green'), ('violet', 'Violet'), ('purple', 'Purple')], default='brown', max_length=30, null=True, verbose_name='Color')),
                ('type', models.CharField(blank=True, choices=[('hard-lumps', 'Separate hard lumps, like nuts (hard to pass)'), ('lumpy', 'Sausage-shaped but lumpy'), ('cracks', 'Like a sausage but with cracks on the surface'), ('smooth', 'Like a sausage or snake, smooth and soft'), ('blobs', 'Soft blobs with clear-cut edges'), ('fluffy', 'Fluffy pieces with ragged edges, a mushy stool'), ('liquid', 'Watery, no solid pieces. Entirely Liquid')], default='smooth', max_length=30, null=True, verbose_name='Type')),
                ('abnormalities', models.CharField(blank=True, choices=[('undigested-food', 'Undigested food remnants'), ('diarrhea', 'Diarrhea'), ('constipation', 'Constipation'), ('others', 'Others')], max_length=30, null=True, verbose_name='Abnormalities')),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Stool',
                'verbose_name_plural': 'Stool Measurements',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Urine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('volume', models.PositiveIntegerField(default=None, help_text='ml', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1700)], verbose_name='Volume')),
                ('color', models.CharField(choices=[('colorless', 'Colorless'), ('yellow-light', 'Light Yellow'), ('yellow', 'yellow'), ('yellow-amber', 'yellow-amber'), ('yellow-brown', 'yellow-brown'), ('amber', 'amber'), ('orange', 'orange'), ('red', 'red'), ('greenish-brown', 'greenish-brown')], default='yellow', max_length=30, verbose_name='Color')),
                ('turbidity', models.CharField(choices=[('clear', 'Clear'), ('slightly', 'Slightly'), ('cloudy', 'Cloudy'), ('turbid', 'Turbid')], default='clear', max_length=30, verbose_name='Turbidity')),
                ('ph', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='pH')),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Urine',
                'verbose_name_plural': 'Urine Measurements',
                'ordering': ['-datetime'],
            },
        ),
        migrations.DeleteModel(
            name='Excretion',
        ),
    ]
