# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='pulseoxymetry',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='stool',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='urine',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
