# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20170817_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='astronaut',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
