# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20171009_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='pulseoxymetry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='pulseoxymetry',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='stool',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='stool',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='urine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='urine',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
    ]
