# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20170817_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressure',
            options={'ordering': ['-datetime'], 'verbose_name': 'Blood Pressure', 'verbose_name_plural': 'Blood Pressure'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['-datetime_start'], 'verbose_name': 'Disease', 'verbose_name_plural': 'Disease'},
        ),
        migrations.AlterModelOptions(
            name='pulseoxymetry',
            options={'ordering': ['-datetime'], 'verbose_name': 'Pulse Oxymetry', 'verbose_name_plural': 'Pulse Oxymetry'},
        ),
        migrations.AlterModelOptions(
            name='stool',
            options={'ordering': ['-datetime'], 'verbose_name': 'Stool', 'verbose_name_plural': 'Stool'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-datetime'], 'verbose_name': 'Temperature', 'verbose_name_plural': 'Temperature'},
        ),
        migrations.AlterModelOptions(
            name='urine',
            options={'ordering': ['-datetime'], 'verbose_name': 'Urine', 'verbose_name_plural': 'Urine'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-datetime'], 'verbose_name': 'Weight', 'verbose_name_plural': 'Weight'},
        ),
        migrations.AlterField(
            model_name='stool',
            name='color',
            field=models.CharField(choices=[('brown', 'Brown'), ('yellow', 'Yellow'), ('gray', 'Gray'), ('pale', 'Pale'), ('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('silver', 'Silver'), ('green', 'Green'), ('violet', 'Violet'), ('purple', 'Purple')], default='brown', max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='stool',
            name='type',
            field=models.CharField(choices=[('hard-lumps', 'Separate hard lumps, like nuts (hard to pass)'), ('lumpy', 'Sausage-shaped but lumpy'), ('cracks', 'Like a sausage but with cracks on the surface'), ('smooth', 'Like a sausage or snake, smooth and soft'), ('blobs', 'Soft blobs with clear-cut edges'), ('fluffy', 'Fluffy pieces with ragged edges, a mushy stool'), ('liquid', 'Watery, no solid pieces. Entirely Liquid')], default='smooth', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='urine',
            name='color',
            field=models.CharField(choices=[('colorless', 'Colorless'), ('yellow-light', 'Light Yellow'), ('yellow', 'Yellow'), ('yellow-amber', 'Yellow Amber'), ('yellow-brown', 'Yellow Brown'), ('amber', 'Amber'), ('orange', 'Orange'), ('red', 'Red'), ('greenish-brown', 'Greenish Brown')], default='yellow', max_length=30, verbose_name='Color'),
        ),
    ]
