# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import habitat._common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20170825_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='pulseoxymetry',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='stool',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='urine',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
