# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170520_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humidity',
            options={'ordering': ['-value']},
        ),
        migrations.AlterModelOptions(
            name='luminosity',
            options={'ordering': ['-value']},
        ),
        migrations.AddField(
            model_name='humidity',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='luminosity',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='luminosity',
            name='value',
            field=models.PositiveSmallIntegerField(default=None, help_text='lumen', verbose_name='Luminosity'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Temperature'),
        ),
    ]
