# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20170521_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luminance',
            name='value',
            field=models.PositiveSmallIntegerField(default=None, help_text='lumen', verbose_name='Luminance'),
        ),
    ]
