# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20170521_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humidity',
            options={'ordering': ['-value'], 'verbose_name': 'Humitdity Measurement', 'verbose_name_plural': 'Humidity'},
        ),
        migrations.AlterModelOptions(
            name='luminance',
            options={'ordering': ['-value'], 'verbose_name': 'Luminance Measurement', 'verbose_name_plural': 'Luminance'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-value'], 'verbose_name': 'Temperature Measurement', 'verbose_name_plural': 'Temperature'},
        ),
    ]
