# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20170713_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonDioxide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('value', models.PositiveSmallIntegerField(help_text='%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Concentration')),
            ],
            options={
                'verbose_name': 'Carbon Dioxide Concentration Measurement',
                'verbose_name_plural': 'Carbon Dioxide Concentration',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='CarbonMonoxide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('value', models.PositiveSmallIntegerField(help_text='%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Concentration')),
            ],
            options={
                'verbose_name': 'Carbon Monoxide Concentration Measurement',
                'verbose_name_plural': 'Carbon Monoxide Concentrations',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('value', models.PositiveSmallIntegerField(help_text='%', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Concentration')),
            ],
            options={
                'verbose_name': 'Oxygen Concentration Measurement',
                'verbose_name_plural': 'Oxygen Concentrations',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='humidity',
            options={'ordering': ['-datetime'], 'verbose_name': 'Humitdity Measurement', 'verbose_name_plural': 'Humidity'},
        ),
    ]
