# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20170719_2220'),
        ('sensors', '0009_auto_20170716_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbondioxide',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Carbon Dioxide Concentration Measurement', 'verbose_name_plural': 'Carbon Dioxide'},
        ),
        migrations.AlterModelOptions(
            name='carbonmonoxide',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Carbon Monoxide Concentration Measurement', 'verbose_name_plural': 'Carbon Monoxide'},
        ),
        migrations.AlterModelOptions(
            name='humidity',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Humitdity Measurement', 'verbose_name_plural': 'Humidity'},
        ),
        migrations.AlterModelOptions(
            name='luminance',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Luminance Measurement', 'verbose_name_plural': 'Luminance'},
        ),
        migrations.AlterModelOptions(
            name='oxygen',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Oxygen Concentration Measurement', 'verbose_name_plural': 'Oxygen'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Temperature Measurement', 'verbose_name_plural': 'Temperature'},
        ),
        migrations.AddField(
            model_name='carbondioxide',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location'),
        ),
        migrations.AddField(
            model_name='carbonmonoxide',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location'),
        ),
        migrations.AddField(
            model_name='humidity',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location'),
        ),
        migrations.AddField(
            model_name='luminance',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location'),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location'),
        ),
    ]
