# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20170719_2220'),
        ('sensors', '0010_auto_20170719_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('value', models.PositiveSmallIntegerField(default=None, help_text='Mbps', verbose_name='Value')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location')),
            ],
            options={
                'verbose_name': 'Internet Speed Measurement',
                'verbose_name_plural': 'Internet Speed',
                'ordering': ['-datetime', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('value', models.PositiveSmallIntegerField(default=None, help_text='mmHg', verbose_name='Pressure')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location')),
            ],
            options={
                'verbose_name': 'Temperature Measurement',
                'verbose_name_plural': 'Temperature',
                'ordering': ['-datetime', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('value', models.PositiveSmallIntegerField(default=None, help_text='Sv - Sievert', verbose_name='Radiation')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location')),
            ],
            options={
                'verbose_name': 'Internet Speed Measurement',
                'verbose_name_plural': 'Internet Speed',
                'ordering': ['-datetime', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('value', models.PositiveSmallIntegerField(default=None, help_text='V', verbose_name='Value')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Sensor Location')),
            ],
            options={
                'verbose_name': 'Voltage Measurement',
                'verbose_name_plural': 'Voltage',
                'ordering': ['-datetime', 'location'],
            },
        ),
    ]
