# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_network_pressure_radiation_voltage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Network Performance Measurement', 'verbose_name_plural': 'Network Performance'},
        ),
        migrations.AlterModelOptions(
            name='pressure',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Pressure Measurement', 'verbose_name_plural': 'Pressure'},
        ),
        migrations.AlterModelOptions(
            name='radiation',
            options={'ordering': ['-datetime', 'location'], 'verbose_name': 'Radiation Measurement', 'verbose_name_plural': 'Radiation'},
        ),
    ]
