# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biolab', '0002_auto_20170331_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='cultivation_method',
            field=models.CharField(choices=[('soil', 'Soil'), ('underwater', 'Underwater'), ('artificial', 'Artificial'), ('hydroponics', 'Hydroponics'), ('aeroponics', 'Aeroponics'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=30, verbose_name='Cultivation method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='planted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Planted'),
        ),
    ]
