# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer_1', models.CharField(max_length=255, verbose_name='Answer 1')),
                ('answer_2', models.CharField(max_length=255, verbose_name='Answer 1')),
                ('answer_3', models.CharField(max_length=255, verbose_name='Answer 1')),
                ('answer_4', models.CharField(max_length=255, verbose_name='Answer 1')),
                ('answer_5', models.CharField(max_length=255, verbose_name='Answer 1')),
                ('answer_6', models.CharField(max_length=255, verbose_name='Answer 1')),
            ],
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.Questionary', verbose_name='Questionary')),
            ],
        ),
        migrations.AddField(
            model_name='openquestion',
            name='questionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.Questionary', verbose_name='Questionary'),
        ),
        migrations.AddField(
            model_name='closedquestion',
            name='questionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.Questionary', verbose_name='Questionary'),
        ),
    ]
