# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Datetime')),
                ('communication_frequency', models.PositiveSmallIntegerField(choices=[(1, 'almost never'), (2, 'rarely'), (3, 'sometimes'), (4, 'moderately'), (5, 'rather often'), (6, 'very often'), (7, 'almost all the time')], verbose_name='How frequently do you communicate with following people?')),
                ('communication_desired', models.PositiveSmallIntegerField(choices=[(1, 'almost never'), (2, 'rarely'), (3, 'sometimes'), (4, 'moderately'), (5, 'rather often'), (6, 'very often'), (7, 'almost all the time')], verbose_name='How often do you want to communicate with following people?')),
                ('personal_preferences', models.PositiveSmallIntegerField(choices=[(1, 'I would rather avoid him/her'), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, 'I would love to with with him/her all the time')], verbose_name='Personal preferences: Please, evaluate the following people according to your preference to interact with them in your free time.')),
                ('work_preferences', models.PositiveSmallIntegerField(choices=[(1, 'I would rather avoid him/her'), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, 'I would love to with with him/her all the time')], verbose_name='Work preferences: Please, evaluate the following people according to your preference to work with them.')),
                ('communication_quality', models.PositiveSmallIntegerField(choices=[(1, 'should always be better'), (2, 'should often be better'), (3, 'should sometimes be better'), (4, 'sufficient'), (5, 'sometimes above average'), (6, 'often above average'), (7, 'always above average')], verbose_name='Evaluate the quality of communication with following people (taking into account its relevance, content, timeliness, etc.).')),
                ('know_already', models.PositiveSmallIntegerField(choices=[(1, 'not at all'), (2, 'not much'), (3, 'moderately'), (4, 'quite well'), (5, 'well'), (6, 'very well'), (7, 'perfectly well')], verbose_name='How well do you know the following people?')),
                ('know_desired', models.PositiveSmallIntegerField(choices=[(1, 'not at all'), (2, 'not much'), (3, 'moderately'), (4, 'quite well'), (5, 'well'), (6, 'very well'), (7, 'perfectly well')], verbose_name='How well do you want to know the following people?')),
                ('cooperation_quality', models.PositiveSmallIntegerField(choices=[(1, 'totally insufficient'), (2, 'often insufficient'), (3, 'sometimes insufficient'), (4, 'sufficient'), (5, 'rather high'), (6, 'high'), (7, 'excellent')], verbose_name='Evaluate the quality of cooperation with the following people?')),
                ('trust', models.PositiveSmallIntegerField(choices=[(1, 'Totally'), (2, 'Very much'), (3, 'A lot'), (4, 'Partly'), (5, 'A little'), (6, 'Not much'), (7, 'Not at all')], verbose_name='How much do you trust the following people?')),
                ('team_atmosphere', models.PositiveSmallIntegerField(choices=[(1, 'Terrible'), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, 'Amazing')], verbose_name='How is the atmosphere within the team?')),
                ('team_misunderstandings', models.PositiveSmallIntegerField(choices=[(1, 'Never'), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, 'Constantly')], verbose_name='Have there been any misunderstandings in the team?')),
                ('discomfort', models.TextField(verbose_name='If applicable, name the source(s) for the discomfort you are experience (e.g. noise, smell, food, sleeping problems, interpersonal conflict, etc.)')),
                ('remarks', models.TextField(verbose_name='You can add any comment or note (e.g. if something important happened, how do you feel etc.)')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='astronaut',
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='astronaut',
            new_name='reporter',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='updated',
        ),
        migrations.AddField(
            model_name='mood',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='repair',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Datetime'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Datetime'),
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
