# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='time',
            field=models.TimeField(help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
