# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0002_auto_20170819_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Datetime')),
                ('datetime_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Datetime')),
                ('datetime_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Datetime')),
                ('severity', models.CharField(choices=[('emergency', 'Emergency - ABORT the mission'), ('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Informative')], default='info', max_length=30, verbose_name='Severity')),
                ('subject', models.CharField(default=None, max_length=100, verbose_name='Subject')),
                ('description', models.TextField(blank=True, default=True, null=True, verbose_name='Description')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Module', verbose_name='Sensor Location')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Security Incident',
                'verbose_name_plural': 'Security',
            },
        ),
        migrations.AlterModelOptions(
            name='mood',
            options={'verbose_name': 'Mood Report', 'verbose_name_plural': 'Mood Reports'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Repair', 'verbose_name_plural': 'Repair Logbook'},
        ),
        migrations.AlterModelOptions(
            name='sleep',
            options={'verbose_name': 'Sleep Log', 'verbose_name_plural': 'Sleep Logbook'},
        ),
    ]
