# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20170731_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='end',
            field=models.DateTimeField(blank=True, default=None, help_text='Leave empty if problem persists.', null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='object',
            field=models.ForeignKey(blank=True, default=None, help_text='Leave empty, if object is not on the list', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='status',
            field=models.CharField(choices=[('broken', 'Broken'), ('fixed', 'Fixed'), ('destroyed', 'Permanently Destroyed')], default=None, max_length=30, verbose_name='Current Status'),
        ),
    ]
