# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20170819_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Communication'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Incident', 'verbose_name_plural': 'Incident'},
        ),
        migrations.AlterModelOptions(
            name='mood',
            options={'verbose_name': 'Mood Report', 'verbose_name_plural': 'Mood'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Repair Log', 'verbose_name_plural': 'Repair'},
        ),
        migrations.AlterModelOptions(
            name='sleep',
            options={'verbose_name': 'Sleep Log', 'verbose_name_plural': 'Sleep'},
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
    ]
