# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20170819_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='communication',
            name='time',
            field=models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='mood',
            name='time',
            field=models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='repair',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='repair',
            name='time',
            field=models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='time',
            field=models.TimeField(default=None, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
    ]
