# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20170819_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
    ]
