# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20170819_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('emergency', 'Emergency - ABORT the simulation'), ('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Informative')], default='info', max_length=30, verbose_name='Severity'),
        ),
    ]
