# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import habitat._common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20170828_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='time',
            field=models.TimeField(default=habitat._common.utils.LunarStandardTime.time, help_text='Lunar Standard Time', verbose_name='Mission Time'),
        ),
    ]
