# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.timezone.models.martian_standard_time


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20170926_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='date',
            field=models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109', max_length=15, verbose_name='Mars Sol Date'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='time',
            field=models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 51099.420109', verbose_name='Coordinated Mars Time'),
        ),
    ]
