# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0007_auto_20170819_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('biohazard', 'Biohazard'), ('chemical', 'Chemical'), ('medical', 'Medical')], default='regular', max_length=30, verbose_name='Waste')),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=4, verbose_name='Weight')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Chemical Waste',
                'verbose_name_plural': 'Chemical Waste',
            },
        ),
    ]
