# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20171010_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('name', models.CharField(blank=None, default=None, max_length=255, null=None, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Sleep Quality',
                'verbose_name_plural': 'Sleep Qualities',
            },
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleep_quality',
            field=models.ManyToManyField(blank=True, default=None, related_name='sleep_quality', to='reporting.SleepQuality', verbose_name='Quality'),
        ),
    ]
