# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20170819_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waste',
            options={'verbose_name': 'Waste', 'verbose_name_plural': 'Waste'},
        ),
    ]
