# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_auto_20171014_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepquality',
            options={'ordering': ['name'], 'verbose_name': 'Sleep Quality', 'verbose_name_plural': 'Sleep Qualities'},
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='sleep_quality',
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleep_events',
            field=models.ManyToManyField(blank=True, default=None, related_name='sleep_events', to='reporting.SleepQuality', verbose_name='Events'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleep_interruptions',
            field=models.ManyToManyField(blank=True, default=None, related_name='sleep_interruptions', to='reporting.SleepQuality', verbose_name='Interruptions'),
        ),
        migrations.AddField(
            model_name='sleepquality',
            name='type',
            field=models.CharField(default='event', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sleepquality',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
