# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0010_auto_20170819_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Mission Date')),
                ('drugs_and_supplements', models.TextField(blank=True, default=None, null=True, verbose_name='Remarks')),
                ('medical_condition', models.TextField(blank=True, default=None, null=True, verbose_name='Medical Condition')),
                ('food', models.TextField(blank=True, default=None, null=True, verbose_name='Food')),
                ('EVA', models.TextField(blank=True, default=None, null=True, verbose_name='EVA')),
                ('medical_experiment', models.TextField(blank=True, default=None, null=True, verbose_name='Medical Experiment')),
                ('mood_and_morale', models.TextField(blank=True, default=None, null=True, verbose_name='Mood and Morale')),
                ('remarks', models.TextField(blank=True, default=None, null=True, verbose_name='Remarks')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Astronaut')),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical',
            },
        ),
    ]
