# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20171014_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='sleep_interrupted',
            field=models.NullBooleanField(default=None, verbose_name='Was your sleep interrupted?'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_events',
            field=models.ManyToManyField(blank=True, default=None, related_name='sleep_events', to='reporting.SleepQuality', verbose_name='Sleep Events'),
        ),
        migrations.AlterField(
            model_name='sleepquality',
            name='type',
            field=models.CharField(choices=[('event', 'Un-interruptive Sleep Event'), ('interruption', 'Sleep Interruption')], default='event', max_length=30, verbose_name='Type'),
        ),
    ]
