# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20171014_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_interrupted',
            field=models.NullBooleanField(choices=[(None, 'Undisclosed'), (True, 'Yes'), (False, 'No')], default=None, verbose_name='Was your sleep interrupted?'),
        ),
    ]
