# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_auto_20171014_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sleepquality',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sleepquality',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sociodynamicreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sociodynamicreport',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sociodynamicreportentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='sociodynamicreportentry',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime [UTC]'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime [UTC]'),
        ),
    ]
