# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_auto_20170325_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='datetime',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Publish Date'),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalnote',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Publish Date'),
        ),
    ]
