# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0004_auto_20170325_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
