# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notepad', '0005_auto_20170325_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='tags',
            field=models.CharField(default='', help_text='Comma separated tags', max_length=255, verbose_name='Tags'),
            preserve_default=False,
        ),
    ]
