# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0006_auto_20170325_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='publish_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
    ]
