# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0007_auto_20170325_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='Slug'),
        ),
    ]
