# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0008_auto_20170325_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=30, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
