# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0009_diaryentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
