# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import habitat.timezone.models.martian_standard_time


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0005_auto_20171009_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('file', models.FileField(upload_to='email/', verbose_name='Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Add Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime')),
                ('date', models.CharField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.date, help_text='example: 51099.420109, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', max_length=15, verbose_name='Mars Sol Date')),
                ('time', models.TimeField(default=habitat.timezone.models.martian_standard_time.MartianStandardTime.time, help_text='example: 16:04:57, <a href="/api/v1/timezone/martian-standard-time/converter/" target="_blank">use converter</a> to calculate from Earth time', verbose_name='Coordinated Mars Time')),
                ('subject', models.CharField(db_index=True, max_length=255, verbose_name='Subject')),
                ('body', models.TextField(blank=True, default=None, null=True, verbose_name='Body')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('to', models.ManyToManyField(db_index=True, related_name='to', to=settings.AUTH_USER_MODEL, verbose_name='To')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Email', verbose_name='Email'),
        ),
    ]
