# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage', 'verbose_name_plural': 'Storage'},
        ),
    ]
