# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='hazard',
            field=models.CharField(choices=[('none', 'None'), ('warning', 'Warning'), ('hazardous', 'Hazardous'), ('toxic', 'Toxic'), ('depress', 'Hazardous'), ('fire', 'Fire'), ('disabled', 'Disabled')], db_index=True, default='none', max_length=30, verbose_name='Hazard'),
        ),
        migrations.AlterField(
            model_name='module',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='m', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='module',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='m', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='module',
            name='plan',
            field=models.CharField(choices=[('ellipsis', 'Ellipsis'), ('rectangle', 'Rectangle'), ('polygon', 'Polygon'), ('other', 'Other')], default='rectangle', max_length=30, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='module',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='m', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Width'),
        ),
    ]
