# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_storage'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='meters', null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='meters', null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='building.Storage', verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(default=None, max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='item',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('solid', 'Solid'), ('liquid', 'Liquid')], default='solid', max_length=30, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='liters', null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='meters', null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=7, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
    ]
