# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edible',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edible',
            name='date',
            field=models.CharField(default=None, help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='edible',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='edible',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Add Datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.CharField(default=' ', help_text='Lunar Standard Time', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified Datetime'),
        ),
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Lunar Standard Time', verbose_name='Time'),
        ),
    ]
