# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170817_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['identifier'], 'verbose_name': 'Item', 'verbose_name_plural': 'Item Database'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.CharField(default=None, max_length=7, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Manufacturer'),
        ),
    ]
