# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170819_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edible',
            name='date',
        ),
        migrations.RemoveField(
            model_name='edible',
            name='time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
    ]
