# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleep',
            options={'ordering': ['-datetime_bedtime'], 'verbose_name': 'Sleep Log', 'verbose_name_plural': 'Sleep Logbook'},
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='datetime_start',
        ),
        migrations.AddField(
            model_name='sleep',
            name='datetime_bedtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When did you go to bed?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='datetime_fall_asleep',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When did you fall asleep?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='datetime_getup',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='When did you get up?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='datetime_wakeup',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='When did you wake up?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='type',
            field=models.CharField(blank=True, choices=[('sleep', 'Sleep'), ('nap', 'Nap')], default=None, max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='wakeup',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Did you wake up at night? If yes, when and for how long (approx.)?'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modules.Module', verbose_name='Location'),
        ),
    ]
