# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20170716_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='wakeup',
        ),
        migrations.AddField(
            model_name='sleep',
            name='dream',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='If you remember what was your dream about?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='ear_plugs',
            field=models.NullBooleanField(default=None, verbose_name='Did you use ear plugs?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='eye_mask',
            field=models.NullBooleanField(default=None, verbose_name='Did you use an eye mask?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='falling_asleep',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='If it took you longer than 10 min to fall asleep, what was the reason?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='last_activity',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='What was the last thing you did before going to sleep?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='night_wakeups',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Did you wake up at night? If yes, when and for how long (approx.)?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleep_amount',
            field=models.CharField(choices=[('sufficient', 'Sufficient'), ('slightly', 'Slightly'), ('somewhat', 'Somewhat'), ('very insufficient', 'Very Insufficient')], default=None, max_length=30, verbose_name='How would you describe the amount of sleep?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleep_drug',
            field=models.NullBooleanField(default=None, verbose_name='Did you use a sleep drug?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleepy',
            field=models.CharField(choices=[('no', 'No'), ('mildly', 'Mildly'), ('considerably', 'Considerably'), ('intensely', 'Intensely')], default=None, max_length=30, verbose_name='Did you feel sleepy during the day?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='sleepy_remarks',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Percent of wake time', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='If yes, how much?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='wakeup_reasons',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='What woke you up in the morning?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='wakeup_remarks',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='If you woke up during the night, why?'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='quality',
            field=models.CharField(choices=[('satisfactory', 'Satisfactory'), ('slightly', 'Slightly Satisfactory'), ('somewhat', 'Somewhat Unsatisfactory'), ('very unsatisfactory', 'Very Unsatisfactory')], default=None, max_length=30, verbose_name='How would you rate your overall quality of sleep?'),
        ),
    ]
