# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0003_auto_20170714_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='album',
            name='content',
            field=models.TextField(default=None, null=True, blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
        migrations.AddField(
            model_name='album',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publish Date'),
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=None, null=True, blank=True, editable=False, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.CharField(blank=True, default=None, help_text='Comma separated tags', max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Title'),
        ),
    ]
