# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20170716_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleep',
            options={'ordering': ['-asleep_bedtime'], 'verbose_name': 'Sleep Log', 'verbose_name_plural': 'Sleep Logbook'},
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='ear_plugs',
            new_name='aid_ear_plugs',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='eye_mask',
            new_name='aid_eye_mask',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='datetime_bedtime',
            new_name='asleep_bedtime',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='falling_asleep',
            new_name='asleep_problems',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='datetime_fall_asleep',
            new_name='asleep_time',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='datetime_getup',
            new_name='getup',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='wakeup_remarks',
            new_name='impediments_remarks',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='datetime_wakeup',
            new_name='wakeup_time',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='night_wakeups',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='sleep_drug',
        ),
        migrations.AddField(
            model_name='sleep',
            name='aid_pills',
            field=models.NullBooleanField(default=None, verbose_name='Did you use a sleep pills?'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='impediments_count',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Minutes', null=True, verbose_name='Did you wake up at night? If you yes, for how long (approx.)?'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='quality',
            field=models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('slightly', 'Slightly Satisfactory'), ('somewhat', 'Somewhat Unsatisfactory'), ('very unsatisfactory', 'Very Unsatisfactory')], default=None, max_length=30, null=True, verbose_name='How would you rate your overall quality of sleep?'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_amount',
            field=models.CharField(blank=True, choices=[('sufficient', 'Sufficient'), ('slightly', 'Slightly'), ('somewhat', 'Somewhat'), ('very insufficient', 'Very Insufficient')], default=None, max_length=30, null=True, verbose_name='How would you describe the amount of sleep?'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleepy',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('mildly', 'Mildly'), ('considerably', 'Considerably'), ('intensely', 'Intensely')], default=None, max_length=30, null=True, verbose_name='Did you feel sleepy during the day?'),
        ),
    ]
