# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20170716_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='sleepy',
            field=models.CharField(choices=[('no', 'No'), ('mildly', 'Mildly'), ('considerably', 'Considerably'), ('intensely', 'Intensely')], default='no', max_length=30, verbose_name='Did you feel sleepy during the day?'),
        ),
    ]
