# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20170714_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_added',
            field=models.DateField(blank=True, null=True, verbose_name='Date Aded'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public?'),
        ),
    ]
