# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20170717_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['-day'], 'verbose_name': 'Mood Report', 'verbose_name_plural': 'Mood Reports'},
        ),
        migrations.RemoveField(
            model_name='mood',
            name='datetime',
        ),
        migrations.AddField(
            model_name='mood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Report About Day'),
        ),
        migrations.AddField(
            model_name='mood',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleep',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='type',
            field=models.CharField(choices=[('sleep', 'Sleep'), ('nap', 'Nap')], default=None, max_length=30, verbose_name='Type'),
        ),
    ]
