# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20170717_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='day_quality',
            field=models.CharField(blank=True, choices=[('very good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('bad', 'Bad'), ('very bad', 'Very Bad')], default=None, max_length=30, null=True, verbose_name='Day Quality'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default=None, max_length=30, null=True, verbose_name='Mood'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='productivity',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default=None, max_length=30, null=True, verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='remarks',
            field=models.TextField(blank=True, default=None, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='stress',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default=None, max_length=30, null=True, verbose_name='Stress'),
        ),
    ]
