# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observation date')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='planted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Planted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.Experiment', verbose_name='Experiment'),
        ),
    ]
