# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_auto_20170331_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['-planted_date']},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-datetime']},
        ),
    ]
