# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_auto_20170520_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-latin_name']},
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='plant',
            name='latin_name',
            field=models.CharField(default=None, help_text='Latin', max_length=255, verbose_name='Latin Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='spicies',
            field=models.CharField(default=None, help_text='Species', max_length=255, verbose_name='Species'),
        ),
    ]
