# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0007_auto_20170521_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['-planted_date'], 'verbose_name': 'Experiment', 'verbose_name_plural': 'Experiments'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-datetime'], 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-latin_name'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
    ]
