# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drag_and_drop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-date_added'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['album'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
