# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.drag_and_drop.models


class Migration(migrations.Migration):

    dependencies = [
        ('drag_and_drop', '0002_auto_20170714_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.RemoveField(
            model_name='album',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='album',
            name='title',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=habitat.drag_and_drop.models.upload_path),
        ),
    ]
