# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=7, verbose_name='Code')),
                ('best_before', models.DateField(verbose_name='Best before')),
                ('calories', models.PositiveSmallIntegerField(help_text='kcal', verbose_name='Calories')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='ml', max_digits=5, null=True, verbose_name='Volume')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='g', max_digits=5, null=True, verbose_name='Net Weight')),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, help_text='g', max_digits=5, null=True, verbose_name='Proteins')),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, help_text='g', max_digits=5, null=True, verbose_name='Carbohydrates')),
                ('fats', models.DecimalField(blank=True, decimal_places=2, help_text='g', max_digits=5, null=True, verbose_name='Fats')),
                ('salt', models.DecimalField(blank=True, decimal_places=2, help_text='g', max_digits=5, null=True, verbose_name='Salts')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=7, verbose_name='Code')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
            ],
        ),
    ]
