# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-best_before'], 'verbose_name': 'Food', 'verbose_name_plural': 'Food Database'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['code'], 'verbose_name': 'Item', 'verbose_name_plural': 'Item Database'},
        ),
    ]
