# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170521_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
