# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-best_before'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products Database'},
        ),
    ]
