# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 13:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import habitat.systems.food.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20170713_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(default=None, editable=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(default=None, editable=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_before',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates_sugars',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Sugars'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('meat', 'Meat')], db_index=True, default=None, max_length=30, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Cholesterol'),
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Coocking Factor'),
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Product', verbose_name='From Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_waste',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Cooking Waste'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats_monounsaturated',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Monounsaturated Fats'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats_polyunsaturated',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Polyunsaturated Fats'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats_saturated',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Saturated Fats'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=habitat.systems.food.models.product.upload_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('custom', 'Custom Made'), ('brand', 'Brand Product'), ('gourmet', 'Gourmet Food'), ('restaurant', 'Restaurant')], db_index=True, default=None, max_length=30, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements_physical_form',
            field=models.CharField(blank=True, choices=[('solid', 'Solid'), ('liquid', 'Liquid')], db_index=True, default=None, max_length=20, null=True, verbose_name='Phisical Form'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements_volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='ml', max_digits=5, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g', max_digits=5, null=True, verbose_name='Net Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_calcium',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Calcium'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_copper',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Copper'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_iodine',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='µg/100g', max_digits=5, null=True, verbose_name='Iodine'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_iron',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Iron'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_magnesium',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Magnesium'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_phosphorus',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Phosphorus'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_potasium',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Potasium'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_selenium',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='µg/100g', max_digits=5, null=True, verbose_name='Selenium'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_sodium',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Sodium'),
        ),
        migrations.AddField(
            model_name='product',
            name='minerals_zinc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Zinc'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins_animal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Animal Proteins'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins_plant',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Plant Proteins'),
        ),
        migrations.AddField(
            model_name='product',
            name='roughage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Roughage'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, editable=False, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_a',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='µg/100g', max_digits=5, null=True, verbose_name='Vitamin A'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_b1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Vitamin B1'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_b12',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='µg/100g', max_digits=5, null=True, verbose_name='Vitamin B12'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_b2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Vitamin B2'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_b6',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Vitamin B6'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_c',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Vitamin C'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='µg/100g', max_digits=5, null=True, verbose_name='Vitamin D'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_e',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Vitamin E'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_folic_acid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='µg/100g', max_digits=5, null=True, verbose_name='Folic Acid'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins_pp',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Vitamin pp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveSmallIntegerField(default=None, help_text='kcal', verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Fats'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='g/100g', max_digits=5, null=True, verbose_name='Proteins'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements_shopping_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_unit', to='food.Unit', verbose_name='Shopping Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='measurements_usage_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usage_unit', to='food.Unit', verbose_name='Usage Unit'),
            preserve_default=False,
        ),
    ]
