# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20170713_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurements_shopping_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_unit', to='food.Unit', verbose_name='Shopping Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurements_usage_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usage_unit', to='food.Unit', verbose_name='Usage Unit'),
        ),
    ]
