# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 13:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20170713_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='kcal', null=True, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('meat', 'Meat')], db_index=True, default=None, max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cooking_waste',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Cooking Waste'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurements_shopping_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_unit', to='food.Unit', verbose_name='Shopping Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurements_usage_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_unit', to='food.Unit', verbose_name='Usage Unit'),
        ),
    ]
