# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import habitat.systems.food.models.meal


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20170713_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(default=None, editable=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Diet',
                'verbose_name_plural': 'Diets',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(default=None, editable=False, verbose_name='Slug')),
                ('preparation_time', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Preparation Time')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default=None, max_length=30, verbose_name='Difficulty')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=habitat.systems.food.models.meal.upload_path, verbose_name='Image')),
                ('type', models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Dinner'), ('tea', 'Tea'), ('dinner', 'Tea'), ('supper', 'Supper')], db_index=True, default=None, max_length=30, verbose_name='Meal Kind')),
                ('diet', models.ManyToManyField(default=None, to='food.Diet', verbose_name='Diet')),
                ('tags', models.ManyToManyField(default=None, to='food.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'ordering': ['-name'],
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kind',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='food.Tag', verbose_name='Tags'),
        ),
    ]
