# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20170713_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('healthy', 'Healthy'), ('sport', 'Sport')], db_index=True, default=None, max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, to='food.Diet', verbose_name='Diet'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default=None, max_length=30, null=True, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='preparation_time',
            field=models.CharField(blank=True, default=None, help_text='Example: 2h + 12h pickiling', max_length=255, null=True, verbose_name='Preparation Time'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='food.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('tea', 'Tea'), ('supper', 'Supper')], db_index=True, default=None, max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='food.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('custom', 'Custom Made'), ('brand', 'Brand Product'), ('gourmet', 'Gourmet Food'), ('restaurant', 'Restaurant')], db_index=True, default=None, max_length=30, verbose_name='Type'),
        ),
    ]
