# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20170713_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(default=None, editable=False, verbose_name='Slug')),
                ('calories', models.PositiveIntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(5000)], verbose_name='Calories')),
                ('breakfast', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='food.Meal', verbose_name='Breakfast')),
                ('brunch', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brunch', to='food.Meal', verbose_name='Brunch')),
                ('diet', models.ManyToManyField(blank=True, default=None, to='food.Diet', verbose_name='Diet')),
                ('lunch', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='food.Meal', verbose_name='Lunch')),
                ('supper', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='supper', to='food.Meal', verbose_name='Supper')),
                ('tea', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='food.Meal', verbose_name='Tea')),
            ],
            options={
                'verbose_name': 'Day Plan',
                'verbose_name_plural': 'Day Plans',
                'ordering': ['-name'],
            },
        ),
    ]
