# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_dayplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='preparation_time',
            field=models.CharField(blank=True, default=None, help_text='Example: 12h pickiling + 2h preparation + 2h cooking', max_length=255, null=True, verbose_name='Preparation Time'),
        ),
    ]
