# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 20:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20170713_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cooking_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Cooking Factor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cooking_product',
            field=models.ForeignKey(blank=True, default=None, help_text='Dry Product Mass = Cooked Product Mass / Cooking Factor [0.0 - 1.0]', null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Product', verbose_name='From Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitamins_pp',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='mg/100g', max_digits=5, null=True, verbose_name='Vitamin PP'),
        ),
    ]
