# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20170714_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(0)], verbose_name='Calories'),
        ),
    ]
