# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_auto_20170719_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='breakfast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='food.Meal', verbose_name='Breakfast'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='brunch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunch', to='food.Meal', verbose_name='Brunch'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='diet',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='food.Diet', verbose_name='Diet'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='lunch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='food.Meal', verbose_name='Lunch'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='supper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supper', to='food.Meal', verbose_name='Supper'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='tea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='food.Meal', verbose_name='Tea'),
        ),
    ]
